/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.byteflux.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("net.fabricmc:fabric-loader:0.16.14")
    compileOnly("org.slf4j:slf4j-api:2.0.9")
}

description = "libby-fabric"
