/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "libby"
include(":libby-bukkit")
include(":libby-paper")
include(":libby-nukkit")
include(":libby-core")
include(":libby-sponge")
include(":libby-bungee")
include(":libby-velocity")
project(":libby-bukkit").projectDir = file("bukkit")
project(":libby-paper").projectDir = file("paper")
project(":libby-nukkit").projectDir = file("nukkit")
project(":libby-core").projectDir = file("core")
project(":libby-sponge").projectDir = file("sponge")
project(":libby-bungee").projectDir = file("bungee")
project(":libby-velocity").projectDir = file("velocity")
