/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.byteflux.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("org.spongepowered:spongeapi:8.1.0")
}

description = "libby-sponge"
