/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.byteflux.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("net.md-5:bungeecord-api:1.19-R0.1-SNAPSHOT")
}

description = "libby-bungee"
