/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.byteflux.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT")
}

description = "libby-paper"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}