/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.kyngs.libby.java-conventions")
}

dependencies {
    api(project(":libby-core"))
    compileOnly("com.velocitypowered:velocity-api:3.1.1")
}

description = "libby-velocity"
